# Generated by Django 3.2.11 on 2024-03-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=50, unique=True)),
                ('banner_status', models.BooleanField(default=False)),
                ('banner_img', models.ImageField(default='', upload_to='Banner/img')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='profile',
            field=models.ImageField(default='', upload_to='user/profile'),
        ),
    ]
