# Generated by Django 3.2.11 on 2024-03-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_classcis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='banner_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='banner_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='banner_status',
            new_name='status',
        ),
    ]
