# Generated by Django 3.2.11 on 2024-03-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('des', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('img', models.ImageField(default='', upload_to='Services/')),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.ImageField(default='', upload_to='Services/'),
        ),
    ]
