# Generated by Django 3.2.11 on 2024-03-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_masessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('img', models.ImageField(default='', upload_to='message/img')),
            ],
        ),
        migrations.AlterField(
            model_name='masessage',
            name='img',
            field=models.ImageField(default='', upload_to='message/img'),
        ),
    ]
