# Generated by Django 3.2.11 on 2024-03-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20240304_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
