# Generated by Django 3.2.11 on 2024-03-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_about_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
