# Generated by Django 3.2.11 on 2024-03-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0014_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='CustomUser',
        ),
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(default='', upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(default='', upload_to='Banner/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='img',
            field=models.ImageField(default='', upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='title',
            name='img',
            field=models.ImageField(default='', upload_to='title/'),
        ),
    ]
