# Generated by Django 3.2.11 on 2024-03-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_profile_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='cource',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
